### ISSUE TITLE
something went wrong in mac high siera

### ISSUE THREAD

**Issue by loki4u** [csanuragjain/APKRepatcher#9]
Getting following error while loading the apk in to tool

```
Dex2Jar: classes.dex to /Users/user/Downloads/APKRepatcher.V1.0.0/Projects/myapk.apk/dex2Jar/classes.jar
java -Xmx1500m -cp .;/Users/user/Downloads/APKRepatcher.V1.0.0/APKRepatcher_lib/dex/* com.cooltrickshome.helper.RunProgramDex dex2Jar /Users/user/Downloads/APKRepatcher.V1.0.0/Projects/myapk.apk/dexFile/classes.dex /Users/user/Downloads/APKRepatcher.V1.0.0/Projects/myapk.apk/dex2Jar/classes.jar 
Error: Could not find or load main class com.cooltrickshome.helper.RunProgramDex
Encountered errors/warnings while running this program
```

**Comment by ezamelczyk** [comment]
Yeah I'm having the same issue:

```
Extracting apk content to [redacted]
java -Xmx1500m -jar /[redacted]/APKRepatcher.V1.0.0/APKRepatcher_lib/apktool/apktool.jar d [redacted].apk -rfso [redacted].apk/apkSource 
I: Using Apktool 2.0.3 on [redacted].apk
I: Copying raw resources...
I: Copying raw classes.dex file...
I: Copying raw classes2.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Process completed successfully
Apk extracted.
Extracting smali files using apkTool [redacted].apk/apkToolSource
java -Xmx1500m -jar [redacted]/APKRepatcher.V1.0.0/APKRepatcher_lib/apktool/apktool.jar d [redacted].apk -fo [redacted].apk/apkToolSource 
I: Using Apktool 2.0.3 on [redacted].apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/ernestzamelczyk/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: font/worksans_medium.ttf
S: Could not decode file, replacing by FALSE value: font/roboto_medium.ttf
S: Could not decode file, replacing by FALSE value: font/sourcesanspro_semibold.ttf
S: Could not decode file, replacing by FALSE value: font/worksans_semibold.ttf
S: Could not decode file, replacing by FALSE value: font/sourcesanspro_italic.ttf
S: Could not decode file, replacing by FALSE value: font/worksans_regular.ttf
S: Could not decode file, replacing by FALSE value: font/sourcesanspro_bold.ttf
S: Could not decode file, replacing by FALSE value: font/sourcesanspro_regular.ttf
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x7f000000
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:502)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:136)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Encountered errors/warnings while running this program
Smali extracted using apktool.
Copying dex file for Analysis
Dex file copied to [redacted].apk/dexFile
Decompiling the dex to jar using dex2jar and thereafter to java source code using JAD
This process will take time
Dex2Jar: classes2.dex to [redacted].apk/dex2Jar/classes2.jar
java -Xmx1500m -cp .;/[redacted]/APKRepatcher.V1.0.0/APKRepatcher_lib/dex/* com.cooltrickshome.helper.RunProgramDex dex2Jar [redacted].apk/dexFile/classes2.dex [redacted].apk/dex2Jar/classes2.jar 
Error: Could not find or load main class com.cooltrickshome.helper.RunProgramDex
Caused by: java.lang.ClassNotFoundException: com.cooltrickshome.helper.RunProgramDex
Encountered errors/warnings while running this program
```

**Comment by csanuragjain** [comment]
Please try the new version 1.0,1 from release section
